version: '3.5'

services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:6.0-alpine-latest
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - ./monitoring/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
    ports:
      - "10051:10051"
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 172.18.0.4

  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:6.0-alpine-latest
    environment:
      - ZBX_LISTEN_PORT=10052
      - ZBX_START_POLLERS=5
      - ZBX_TIMEOUT=30
    ports:
      - "10052:10052"
    networks:
      default:
        ipv4_address: 172.18.0.2

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.0-alpine-latest
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=America/Fortaleza
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - zabbix-server
    networks:
      default:
        ipv4_address: 172.18.0.5

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.18.0.6

  app:
    build: .
    container_name: minha-aplicacao-java
    ports:
      - "8081:8080"
      - "9010:9010"
      - "10050:10050"
    volumes:
      - ./monitoring/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf
      - ./monitoring/entrypoint.sh:/entrypoint.sh
    networks:
      default:
        ipv4_address: 172.18.0.3

volumes:
  mysql_data:
  pg_data:

networks:
  default:
    name: zabbix_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16